#!/usr/local/bin/perl
###########################################
# licensizer 
# 2011, Mike Schilli <cpan@perlmeister.com>
###########################################
use strict;
use warnings;
use Getopt::Std;
use Pod::Usage;

use vars qw($CVSVERSION);

$CVSVERSION = '$Revision: 1.12 $';

getopts("hv", \my %opts);
pod2usage() if $opts{h};
if($opts{v}) {
    my ($version) = $CVSVERSION =~ /(\d\S+)/;
    die "$0 $version\n";
}

__END__

=head1 NAME

    licensizer - blah blah blah

=head1 SYNOPSIS

    licensizer -xyz

=head1 OPTIONS

=over 8

=item B<-x>

Prints this manual page in text format.

=back

=head1 DESCRIPTION

licensizer blah blah blah.

=head1 EXAMPLES

  $ licensizer -x foo bar

=head1 LEGALESE

Copyright 2011 by Mike Schilli, all rights reserved.
This program is free software, you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 AUTHOR

2011, Mike Schilli <cpan@perlmeister.com>
